= Asciidoctor Mallard: A Project Mallard converter for AsciiDoc
// Settings:
:experimental:
:idprefix:
:idseparator: -
// Aliases:
:project-name: Asciidoctor Mallard
:project-handle: asciidoctor-mallard
// URIs:
:uri-project: https://github.com/asciidoctor/asciidoctor-mallard
:uri-project-repo: https://github.com/asciidoctor/asciidoctor-mallard
:uri-project-issues: {uri-project-repo}/issues
:uri-rvm: http://rvm.io
:uri-asciidoctor: http://asciidoctor.org
:repo-base-uri: {uri-project-repo}/blob/master/
ifdef::env-github[:repo-base-uri: link:]
:uri-notice: {repo-base-uri}NOTICE.adoc
:uri-license: {repo-base-uri}LICENSE.adoc
:uri-worklog: {repo-base-uri}WORKLOG.adoc

.Project status
CAUTION: {project-name} is currently _alpha_ software.
Use accordingly.
Though the bulk of AsciiDoc content is converted, there's still work needed to fill in gaps where conversion is incomplete, incorrect or not implemented.
Once it's ready, the project will be moved into the Asciidoctor organization on GitHub.

== Notable Features

* Direct AsciiDoc to Mallard conversion

== Missing Features

See {uri-worklog}[WORKLOG].

== Prerequisites

All that's needed is Ruby 2.0 or better (2.2 recommended) and a few RubyGems, which we explain how to install in the next section.

To check you have Ruby available, use the `ruby` command to query the version installed:

 $ ruby --version

If you're using {uri-rvm}[RVM], we recommend creating a new gemset to work with Asciidoctor and {project-name}:

 $ rvm use 2.2@asciidoctor-mallard --create

We like RVM because it keeps the dependencies required by various projects isolated.

== Getting Started

The {project-name} project is published in pre-release on RubyGems.org.
You can either install the pre-release version using the following command:

 $ gem install --pre asciidoctor-mallard

Assuming all the required gems install properly, verify you can run the `asciidoctor-mallard` script:

 $ asciidoctor-mallard -v

If you see the version of Asciidoctor Mallard printed, you're ready to use {project-name}!

Skip ahead to the <<example-asciidoc-document>> section to start putting {project-name} to use.
Alternatively, you can follow the steps below to install the project from source.

=== Retrieve the source code

You can retrieve the {project-name} project in one of two ways:

. Clone the git repository
. Download a zip archive of the repository

==== Option 1: Fetch using git clone

If you want to clone the git repository, simply copy the {uri-project-repo}[GitHub repository URL] and pass it to `git clone` command:

 $ git clone https://github.com/asciidoctor/asciidoctor-mallard

Next, change to the project directory:

 $ cd asciidoctor-mallard

==== Option 2: Download the archive

If you want to download a zip archive, click the btn:[Download Zip] button on the right-hand side of the repository page on GitHub.
Once the download finishes, extract the archive, open a console and change to that directory.

TIP: Instead of working out of the {project-handle} directory, you can simply add the absolute path of the [path]_bin_ directory to your `PATH` environment variable.

We'll leverage the project configuration to install the necessary dependencies.

=== Install the Dependencies

The dependencies needed to use {project-name} are defined in the [file]_Gemfile_ at the root of the project.
We can use Bundler to install the dependencies for us.

To check you have Bundler available, use the `bundle` command to query the version installed:

 $ bundle --version

If it's not installed, use the `gem` command to install it.

 $ gem install bundler

Then use the `bundle` command to install the project dependencies:

 $ bundle

Assuming all the required gems install properly, verify you can run the `asciidoctor-mallard` script using Ruby:

 $ ruby ./bin/asciidoctor-mallard -v

If you see the version of Asciidoctor Mallard printed, you're ready to use {project-name}!

Let's grab an AsciiDoc document to distill.

=== Example AsciiDoc document

If you don't already have an AsciiDoc document, you can use the [file]_example.adoc_ file found in the examples directory of this project.

.example.adoc
[source,asciidoc]
....
= Document Title
Doc Writer <doc@example.com>
:doctype: book
:source-highlighter: coderay
:listing-caption: Listing

A simple http://asciidoc.org[AsciiDoc] document.

== Introduction

A paragraph followed by a simple list with square bullets.

[square]
* item 1
* item 2
....

It's time to convert the AsciiDoc document directly to Mallard.

=== Convert AsciiDoc to Mallard

Converting to Mallard is a simple as running the `./bin/asciidoctor-mallard` script using Ruby and passing our AsciiDoc document as the first argument.

 $ ruby ./bin/asciidoctor-mallard example.adoc

When the script completes, you should see the file [file]_example.page_ in the same directory.

IMPORTANT: You'll need to the `coderay` gem installed to run this example since it uses the `source-highlighter` attribute with the value of `coderay`.

Open the [file]_example.page_ file with `yelp` to see the result.

You're also encouraged to try converting this link:README.adoc[README] as well as the documents in the examples directory to see more of what {project-name} can do.

== Contributing

In the spirit of free software, _everyone_ is encouraged to help improve this project.

To contribute code, simply fork the project on GitHub, hack away and send a pull request with your proposed changes.

Feel free to use the {uri-project-issues}[issue tracker] or http://discuss.asciidoctor.org[Asciidoctor mailing list] to provide feedback or suggestions in other ways.

== Authors

{project-name} was written by https://github.com/bk2204[brian m. carlson] on behalf of the Asciidoctor Project.
It is derived in part from the https://github.com/zykh/mallard-backend[AsciiDoc Mallard Backend] and the Asciidoctor DocBook and PDF backends.

== Copyright

Copyright (C) 2013-2015 Daniele Pezzini, brian m. carlson, and the Asciidoctor Project.
Free use of this software is granted under the terms of the MIT License.

For the full text of the license, see the {uri-license}[LICENSE] file.
Refer to the {uri-notice}[NOTICE] file for information about third-party Open Source software in use.
